clipablewire.cpp: Dropping usage of register storage class
The register storage class has been depreacted in C++14 and completely
removed in C++17. Thus resulting in buils errors such as:

clipablewire.cpp:55:2: error: ISO C++17 does not allow register storage class specifier [-Wregister]

Refer: https://en.cppreference.com/w/cpp/language/storage_duration
Bug: https://bugs.gentoo.org/898070
Signed-off-by: Brahmajit Das <brahmajit.xyz@gmail.com>